services:
  web:
    build:
      context: ./front
      dockerfile: Dockerfile  # Utilise le Dockerfile de développement
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app  # Monte le code source en volume
      - /app/node_modules  # Ignore node_modules pour éviter les conflits
    depends_on:
      - api
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0
    command: [ "npm", "run", "dev" ] # Démarre Next.js en mode dev
    restart: unless-stopped

  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    restart: unless-stopped

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - web
      - api