CREATE TABLE IF NOT EXISTS POSTS (
    ID TEXT NOT NULL PRIMARY KEY,
    CONTENT TEXT NOT NULL,
    USER_ID TEXT NOT NULL ,
    CREATED_AT TEXT NOT NULL,
    UPDATED_AT TEXT NULL,
    IMAGE TEXT NULL UNIQUE,
    TAG TEXT NULL,
    GROUP_ID TEXT NULL,
    PRIVACY INT DEFAULT 1, -- 0 PRIVÉ / 1 SEMI-PRIVÉE / 2 PUBLIC / FAUT CREE UNE TABLE POUR STOCKER LES UTILISATEURS PRIVÉ
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);