CREATE TABLE IF NOT EXISTS REQUEST_FOLLOW (
    ID TEXT NOT NULL PRIMARY KEY,
    RECEIVER_ID TEXT NOT NULL,
    ASKER_ID TEXT NOT NULL,
    STATUS TEXT NOT NULL CHECK ( STATUS IN ('pending','refused','accepted') ),
    CREATED_AT TEXT NOT NULL,
    FOREIGN KEY (RECEIVER_ID) REFERENCES USER(ID),
    FOREIGN KEY (ASKER_ID) REFERENCES USER(ID)
)