CREATE TABLE IF NOT EXISTS LIST_PRIVATE_POST (
    ID TEXT NOT NULL PRIMARY KEY UNIQUE,
    POST_ID TEXT NOT NULL,
    USER_ID TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL,
    FOREIGN KEY (POST_ID) REFERENCES POSTS (ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
)