CREATE TABLE IF NOT EXISTS COMMENT_EVENT (
    ID TEXT NOT NULL PRIMARY KEY,
    COMMENT_ID TEXT NOT NULL,
    USER_ID TEXT NOT NULL,
    LIKED TEXT DEFAULT NULL CHECK (LIKED IN ('liked', 'disliked') OR LIKED IS NULL ),
    CREATED_AT TEXT NOT NULL,
    UPDATE_AT TEXT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (COMMENT_ID) REFERENCES COMMENT(ID)
);