CREATE TABLE IF NOT EXISTS SESSION (
    SESSION_ID TEXT NOT NULL PRIMARY KEY,
    USER_ID TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL,
    EXPIRE_AT TEXT NOT NULL,
    FOREIGN KEY(USER_ID) REFERENCES USER(ID)
);