CREATE TABLE IF NOT EXISTS POST_EVENT (
    ID TEXT NOT NULL PRIMARY KEY,
    POST_ID TEXT NOT NULL,
    USER_ID TEXT NOT NULL,
    LIKED TEXT DEFAULT NULL CHECK (LIKED IN ('liked', 'disliked') OR LIKED IS NULL ),
    CREATED_AT TEXT NOT NULL,
    UPDATE_AT TEXT NULL,
    FOREIGN KEY (POST_ID) REFERENCES POSTS(ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON DELETE CASCADE 
);