CREATE TABLE IF NOT EXISTS COMMENT (
    ID TEXT NOT NULL UNIQUE PRIMARY KEY,
    POST_ID TEXT NOT NULL,
    USER_ID TEXT NOT NULL,
    CONTENT TEXT NOT NULL,
    IMAGE TEXT NULL ,
    CREATED TEXT NOT NULL,
    UPDATED_AT  TEXT NULL,
    FOREIGN KEY (POST_ID) REFERENCES POSTS(ID) ON DELETE CASCADE ,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON DELETE CASCADE
);