CREATE TABLE IF NOT EXISTS FOLLOWERS (
    ID TEXT NOT NULL PRIMARY KEY,
    USER_ID TEXT NOT NULL,
    FOLLOWERS TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (FOLLOWERS) REFERENCES USER(ID)
)