CREATE TABLE IF NOT EXISTS GROUPS_EVENT(
    ID TEXT NOT NULL PRIMARY KEY ,
    GROUP_ID TEXT NOT NULL,
    SENDER TEXT NOT NULL,
    DATE_EVENT TEXT NOT NULL,
    DESC TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL,
    FOREIGN KEY (SENDER) REFERENCES USER(ID),
    FOREIGN KEY (GROUP_ID) REFERENCES ALL_GROUPS(ID)
)