CREATE TABLE IF NOT EXISTS GROUPS_EVENT(
    ID TEXT NOT NULL PRIMARY KEY UNIQUE ,
    GROUP_ID TEXT NOT NULL,
    SENDER TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    OPTION_A TEXT NOT NULL,
    OPTION_B TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL,
    FOREIGN KEY (SENDER) REFERENCES USER(ID),
    FOREIGN KEY (GROUP_ID) REFERENCES ALL_GROUPS(ID)
)