CREATE TABLE IF NOT EXISTS MESSAGES (
    ID TEXT NOT NULL PRIMARY KEY,
    SENDER_ID TEXT NOT NULL,
    CONVERSATION_ID TEXT NOT NULL,
    CONTENT TEXT,
    SEEN INTEGER DEFAULT 0,
    TYPE INTEGER NOT NULL, -- 0 = texte, 1 = image
    CREATED_AT TEXT NOT NULL,
    FOREIGN KEY (SENDER_ID) REFERENCES USER(ID),
    FOREIGN KEY (CONVERSATION_ID) REFERENCES CONVERSATIONS(ID)
);