CREATE TABLE IF NOT EXISTS CONVERSATION_MEMBERS (
CONVERSATION_ID TEXT NOT NULL,
USER_ID TEXT NOT NULL,
FOREIGN KEY (CONVERSATION_ID) REFERENCES CONVERSATIONS(ID),
FOREIGN KEY (USER_ID) REFERENCES USER(ID),
PRIMARY KEY (CONVERSATION_ID, USER_ID)
);