CREATE TABLE IF NOT EXISTS GROUPS_MEMBERS (
    ID TEXT NOT NULL PRIMARY KEY UNIQUE ,
    USER_ID TEXT NOT NULL,
    GROUP_ID TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (GROUP_ID) REFERENCES ALL_GROUPS(ID)
)