CREATE TABLE IF NOT EXISTS ALL_GROUPS (
    ID TEXT NOT NULL PRIMARY KEY,
    TITLE TEXT NOT NULL,
    DESC TEXT NOT NULL,
    OWNER TEXT NOT NULL,
    IMAGE TEXT NULL,
    CREATED_AT TEXT NOT NULL,
    FOREIGN KEY (OWNER) REFERENCES USER(ID)
);