CREATE TABLE IF NOT EXISTS ASK_GROUP (
    ID TEXT NOT NULL PRIMARY KEY UNIQUE,
    ASKER TEXT NOT NULL,
    RECEIVER TEXT NOT NULL,
    GROUP_ID TEXT NOT NULL,
    ACCEPTED INT NOT NULL DEFAULT 0 CHECK ( 0 OR 1 ), -- 0 waiting // 1 accepted
    CREATED_AT TEXT NOT NULL,
    FOREIGN KEY (ASKER) REFERENCES USER(ID),
    FOREIGN KEY (RECEIVER) REFERENCES USER(ID)
)