CREATE TABLE IF NOT EXISTS RESPONSE_EVENT (
    ID TEXT NOT NULL PRIMARY KEY,
    USER_ID TEXT NOT NULL,
    RESPONSE INT NOT NULL CHECK (RESPONSE = 1 OR RESPONSE = 2),
    EVENT_ID TEXT NOT NULL,
    GROUP_ID TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL DEFAULT (DATETIME('now')),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (EVENT_ID) REFERENCES GROUPS_EVENT(ID),
    FOREIGN KEY (GROUP_ID) REFERENCES ALL_GROUPS(ID)
);