CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
    ID TEXT NOT NULL PRIMARY KEY UNIQUE,
    TYPE TEXT NOT NULL CHECK(TYPE IN ('LIKE', 'DISLIKE', 'COMMENT', 'COMMENT_LIKE', 'COMMENT_DISLIKE', 'ASK_FOLLOW', 'ASK_GROUP', 'INVITE_GROUP')), -- Like Dislike/ Comment Like Dislike / Followers Ask / ASK GROUP C'EST L'ID ASK GROUP
    USER_ID TEXT NOT NULL, -- La personne a qui envoyer la notif
    ID_TYPE TEXT NOT NULL,
    READ INT DEFAULT 0 NOT NULL CHECK ( READ IN (0,1)),
    CREATED_AT TEXT NOT NULL DEFAULT (DATETIME('now')),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
)