CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
    ID TEXT NOT NULL PRIMARY KEY,
    TYPE TEXT NOT NULL,
    USER_ID TEXT NOT NULL,
    READ INT DEFAULT 0 NOT NULL,
    CREATED_AT TEXT NOT NULL DEFAULT DATETIME('now'),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);